Masuda accounts
KazukiYokoyama/PHP_Study pull request #13
Opened 2019-03-05 03:43 UTC by utugishinra

アカウント登録画面を実装しました。

2019-03-05 14:37 UTC, KazukiYokoyama commented
確認したところ、アカウント登録の機能について、幾つか満たされていないものがあります。

・アカウント登録に成功したら、アカウント登録完了に画面遷移する。
・既に登録されているアカウントの場合、「既に登録されているアカウントです」の文言を表示する。

上記を満たすよう修正をお願いします。
あともう少しだ。頑張って！

参考：
https://github.com/KazukiYokoyama/PHP_Study/wiki/%E3%82%A2%E3%82%AB%E3%82%A6%E3%83%B3%E3%83%88%E7%99%BB%E9%8C%B2

2019-03-10 04:03 UTC, KazukiYokoyama requested changes

2019-03-10 04:03 UTC, KazukiYokoyama commented on .vscode/launch.json
> +{
このファイルはローカルの開発環境だけで使用されるものです。
基本的に、各自の環境でのみ使う（更新される）ファイルはGitの追跡対象外にします。
.gitignoreファイルを追加し、.vscodeディレクトリを追跡しないようにしましょう。

参考：https://qiita.com/anqooqie/items/110957797b3d5280c44f

2019-03-10 04:03 UTC, KazukiYokoyama commented on etc/Blog.sql
> +	`email` VARCHAR(100) NULL DEFAULT NULL COMMENT 'メールアドレス',
account_nameとemailの属性にUNIQUEを追加するだけでも良いよ。
（やってることは同じ）

```suggestion
	`account_name` VARCHAR(20) NULL DEFAULT NULL UNIQUE COMMENT 'アカウント名',
	`email` VARCHAR(100) NULL DEFAULT NULL UNIQUE COMMENT 'メールアドレス',
```

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +            $input_check = new Account();
コメントが不適切かもしれません。
実際には「Account」classのコンストラクタ内で入力チェックを行っています。
ここでは入力チェックの結果（エラーメッセージ等）を取得しています。

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +                $errormessage = $input_check->Get_errorMessage();
$input_check->Insert_Accounts();
↑これを意訳すると、
「入力チェック」インスタンスの「アカウント登録」メソッドを実行する。となります。
ちょっと分かりづらいので、インスタンス名を変更した方が良いかもしれません。

例えば、$account->InsertAccount();とすると、
「アカウント」インスタンスの「アカウント登録」メソッドを実行する。となります。

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +class Account {
classにもコメントをつけましょう。
特にこのclassは名前がシンプルな為、何を行うのか推察することが難しいです。

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +    private $errorflg;                  // エラーフラグ
$errorflgちゃん、どこにも使われてないね…

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +    function Insert_Accounts(){
コメントぉ…(´・ω・｀)

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +                echo "<script>alert('アカウントの登録に失敗しました。');</script>";
すみません。純粋な疑問ですが、この処理が実行される契機ってどのようなものが考えられますか？
論理的にはSQL実行の結果、登録されたデータが無ければ、これが実行されると思うのですが…

単純にAccountsへのINSERTが失敗した場合、PDOExceptionのエラーでcatchの方へ流れてしまうので…

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +            $this->errorMessage .= 'データベース更新エラー\n'.addslashes($e->getMessage()).'。';
特に自作していないモジュールの例外をcatchする時は要注意です！

当然ですが、$eの中にはPDOException内で定義されたエラーメッセージが入っています。
しかし、そのエラーメッセージは、このサービスに対しては何の配慮もない内容です。
今回の場合、UNIQUEキー重複が発生すると、DBに実際に定義されているカラム名が表示されます。
エラーによってはDBの内容が類推可能となる内容が出力されてしまう可能性もあり、攻撃を受ける起点になる事もあります。

今回の場合は、画面には「アカウントの登録に失敗しました」と出力しておき、PDOExceptionからのエラーメッセージはphpのエラーログに出力するのが良いでしょう。

```suggestion
            error_log("[". date('Y-m-d H:i:s') . "]アカウント登録エラー：".addslashes($e->getMessage())."\n", 3, "/var/log/php/php_error.log");
            $this->errorMessage .= 'アカウントの登録に失敗しました。\nサイトの管理者に連絡してください。';
```

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +    protected function Input_check() {
コメントぉ…(´・ω・｀)

protectedは、「このclassを継承した子classでも使用できます」という宣言です。
このclassがそもそも継承させる事を目的としない場合は、protected宣言は不要です。

Input_check()はこのclass内だけで使用しているみたいなので、
privateという宣言にすると、外部からは参照できなくなります。

```suggestion
    private function Input_check() {
```

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +            $this->account_name_errorMessage .= '<p>アカウント名を入力してください。</p>';
好みかと思うんだけど、エラーメッセージを記述する入力チェックに「～チェック」ってコメントは要らないと思うんだよね。エラーメッセージに書いてるし…

何の項目を入力チェックしているかっていうコメントがあれば良いと思います。

2019-03-10 04:03 UTC, KazukiYokoyama commented on models/register.php
> +            $this->errorMessage = array(
私の感想としては、$errorMessageの内容が分かりづらいのではないかと感じます。
特に加工しないPDOExceptionの例外情報が欲しいのであれば、
$this->errorMessage = $eでも良いかと思います。

もう少し可読性を上げるための手段として、このようなものはどうでしょう？
```suggestion
            $this->errorMessage = '登録エラー';
            if($e->errorInfo[1] == 1062){
                        $this->errorMessage = '既に登録されているアカウントです！';
            }
```

2019-03-11 12:20 UTC, utugishinra commented on .vscode/launch.json
> +{
了解しました。
gitの追跡リストから.vscodeを取り除きました。

2019-03-11 12:21 UTC, utugishinra commented on etc/Blog.sql
> +	`email` VARCHAR(100) NULL DEFAULT NULL COMMENT 'メールアドレス',
確かにそうですね。
ファイル内を見直して追加部分のみに修正しました。

2019-03-11 12:37 UTC, utugishinra commented on models/register.php
> +            $input_check = new Account();
修正しました。

2019-03-12 03:41 UTC, utugishinra commented on models/register.php
> +                echo "<script>alert('アカウントの登録に失敗しました。');</script>";
すみません、コードの消し忘れです。消去しておきます。

2019-03-12 03:43 UTC, utugishinra commented on models/register.php
> +                $errormessage = $input_check->Get_errorMessage();
了解しました。確かに分かりにくかったのでaccountに修正します。

2019-03-12 03:45 UTC, utugishinra commented on models/register.php
> +                echo "<script>alert('アカウントの登録に失敗しました。');</script>";
すみません、記述ミスです。修正しておきます。

2019-03-12 03:51 UTC, utugishinra commented on models/register.php
> +            $this->errorMessage .= 'データベース更新エラー\n'.addslashes($e->getMessage()).'。';
了解しました、気を付けます。
今回はログ保存と表示を修正しておきます。

2019-03-12 11:51 UTC, utugishinra commented on models/register.php
> +            $this->account_name_errorMessage .= '<p>アカウント名を入力してください。</p>';
コメントを修正しました。あと、細かいかもだけどコメント化に使っている記号を統一しときます。

2019-03-12 12:05 UTC, utugishinra commented on models/register.php
> +            $this->errorMessage = array(
未加工の情報はログ出力する形式にしました。表示メッセージは上記の記述にしておきます。

2019-03-12 12:52 UTC, KazukiYokoyama commented on .vscode/launch.json
> +{
ＯＫです！

2019-03-12 12:59 UTC, KazukiYokoyama commented on etc/Blog.sql
> +	`email` VARCHAR(100) NULL DEFAULT NULL COMMENT 'メールアドレス',
やったぜ！コードが短縮されると嬉しいね！

2019-03-12 13:02 UTC, KazukiYokoyama commented on models/register.php
> +            $this->errorMessage .= 'データベース更新エラー\n'.addslashes($e->getMessage()).'。';
ＯＫです。直ってるの確認しました。

2019-03-12 13:03 UTC, KazukiYokoyama commented on models/register.php
> +            $this->errorMessage = array(
ＯＫです。確認しました。

2019-03-12 13:18 UTC, KazukiYokoyama commented on models/register.php
> +            $input_check = new Account();
ごめん、書き方が悪かったね。
ここまで書いたんだから、この部分はこっちでコミットするっぺ。

```
           //  アカウント登録処理を開始
            $input_check = new Account();

           //  入力チェックの結果を取得する
            $this->page_data['username_errorMessage'] = $input_check->Get_account_name_errorMessage();
            $this->page_data['email_errorMessage'] = $input_check->Get_email_errorMessage();
            $this->page_data['password_errorMessage'] = $input_check->Get_password_errorMessage();

           //  入力チェックの結果エラーの判定
           if( !$this->page_data['username_errorMessage'] && 
               !$this->page_data['email_errorMessage'] && 
               !$this->page_data['password_errorMessage'])
            {
                      //  入力されたアカウントをDBに保存する処理…
            }
```

2019-03-12 13:23 UTC, KazukiYokoyama commented on models/register.php
> +            $this->account_name_errorMessage .= '<p>アカウント名を入力してください。</p>';
あれ、この修正コミットしてる？

2019-03-12 13:42 UTC, KazukiYokoyama commented on models/register.php
> +            $this->account_name_errorMessage .= '<p>アカウント名を入力してください。</p>';
あがってきた！ＯＫです！

2019-03-12 13:44 UTC, KazukiYokoyama commented on models/register.php
> +                echo "<script>alert('アカウントの登録に失敗しました。');</script>";
なるほど。承知しました。

2019-03-12 13:45 UTC, KazukiYokoyama commented on models/register.php
> +                $errormessage = $input_check->Get_errorMessage();
ＯＫ！確認しました。

2019-03-12 13:55 UTC, KazukiYokoyama requested changes

2019-03-12 13:55 UTC, KazukiYokoyama commented on models/register.php
> +            error_log("[". date('Y-m-d H:i:s') . "]アカウント登録エラー：".addslashes($e->getMessage())."\n", 3, "/var/log/php/php_error.log");
アカウントの重複による登録失敗は、業務処理の一環なので、エラーログには出さないようにしましょう。
後だしで申し訳ないが (´・ω・`) 一つそういう事で頼む。

原則としてエラーログには、プログラムのロジックエラーと、それを解析するために必要な情報を出力するのが良いと思います。

なので、アカウントの重複による登録失敗以外のエラーをログに書き出すように修正してください。

2019-03-12 14:32 UTC, utugishinra commented on models/register.php
> +            error_log("[". date('Y-m-d H:i:s') . "]アカウント登録エラー：".addslashes($e->getMessage())."\n", 3, "/var/log/php/php_error.log");
ほほい、了解

2019-03-12 23:51 UTC, KazukiYokoyama commented on models/register.php
> +            error_log("[". date('Y-m-d H:i:s') . "]アカウント登録エラー：".addslashes($e->getMessage())."\n", 3, "/var/log/php/php_error.log");
ＯＫやで！

2019-03-12 23:55 UTC, KazukiYokoyama approved these changes

2019-03-13 00:05 UTC, merged